<?php
	$sayi1=10;
	$sayi2=6;
	$sonuc1=$sayi1/$sayi2;
	$sonuc2=ceil($sonuc1);
	$sonuc3=floor($sonuc1);
	$sonuc4=round($sonuc1);
	$sonuc5=round($sonuc1,2);
	$sonuc6=sqrt(25);
	echo($sonuc1);
	echo("<br>".$sonuc2);
	echo("<br>".$sonuc3);
	echo("<br>".$sonuc4);
	echo("<br>".$sonuc5);
?>